=== Image
This section describes how to prepare and build Docker image for the VPN proxy.

==== Preparing OpenVPN Profiles and Credentials
The container will need access to the OpenVPN profiles and your VPN credentials, to establish the VPN connection.
These files will be stored on disk and mounted inside the container as volumes.

First, create a directory named `silverbox` (or choose a different name if you like) under the `root` user's home,
and set permissions so that only `root` user can effectively use it:

----
sudo mkdir /root/silverbox
sudo chmod 700 /root/silverbox
----

This directory will be used to hold files that need to be persistently stored on the server,
but contain sensitive data.
It is not just for his VPN proxy container, but for other services provided by the server as well.

Next, create a `vpn` directory, which will hold files related to the VPN connections:

----
sudo mkdir /root/silverbox/vpn
sudo chmod 700 /root/silverbox/vpn
----

Inside it, create `auth` directory:

----
sudo mkdir /root/silverbox/vpn/auth
sudo chmod 700 /root/silverbox/vpn/auth
----

Inside the `auth` directory create a `credentials` file, containing two lines:

. First line is the VPN username
. Second line is the VPN password

Set the following permissions on this file (marks file as read only and only readable by `root`):

----
sudo chmod 400 /root/silverbox/vpn/auth/credentials
----

Next, create a `proxy` directory under the `vpn`:

----
sudo mkdir /root/silverbox/vpn/proxy
sudo chmod 700 /root/silverbox/vpn/proxy
----

And copy all OpenVPN profile files (`*.ovpn`) that you want to use for SOCKS5 over VPN proxy into it
(you can have multiple files as exit point rotation will be configured).

NOTE: At any time, if you want only to use specific profile, create a symlink named `profile` pointing to desired
profile. For example `ln -s SOME_PROFILE.ovpn profile`.
Make sure the link is relative and not absolute: otherwise it won't work inside the container.

==== Creating Docker Network
Using separate Docker network to run VPN-related workloads offers some convenience, isolation,
and also will force Docker to use embedded DNS server which will forward all DNS queries to the host DNS server.

To create Docker bridge network named `vpn` do:

[subs="attributes+"]
----
sudo docker network create --driver=bridge --subnet={SB_VPN_SUBNET} vpn # <1>
----
<1> Replace `{SB_VPN_SUBNET}` with the some subnet for the Docker VPN network. For example: `172.18.0.0/24`.

==== Preparing Image Files
First, create a directory named `containers` under the `/root/silverbox`:

----
sudo mkdir /root/silverbox/containers
sudo chmod 700 /root/silverbox/containers
----

This directory will contain everything required to build different images for Docker containers
(for VPN proxy and other containers).

Inside it, create a directory for the VPN proxy container:

----
sudo mkdir /root/silverbox/containers/vpn-proxy
sudo chmod 700 /root/silverbox/containers/vpn-proxy
----

Create a directory where the VPN proxy container will store its host identity SSH key,
so that it will be persistent between the container upgrades.

----
sudo mkdir /root/silverbox/containers/vpn-proxy/host-key
sudo chmod 700 /root/silverbox/containers/vpn-proxy/host-key
----

Inside the `vpn-proxy` directory, create a file named `docker-compose.yaml` with the following content:

./root/silverbox/containers/vpn-proxy/docker-compose.yaml
[source,yaml,subs="attributes+"]
----
version: '3.5'

networks:
  default:
    name: {SB_VPN_SUBNET} # <1>
    external: true

services:
  vpn-proxy:
    container_name: vpn-proxy
    build:
      context: /root/silverbox/containers/vpn-proxy
      args:
        version: '{SB_ALPINE_VERSION}' # <2>
    restart: on-failure:15
    logging:
      driver: json-file
      options:
        max-size: 10mb
    ports:
      - {SB_IP}:{SB_VPN_PROXY_PORT}:{SB_VPN_PROXY_PORT}/tcp # <3>
    networks:
      default:
        ipv4_address: {SB_VPN_PROXY_ADDR} # <4>
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - /root/silverbox/vpn/proxy:/vpn-profiles
      - /root/silverbox/vpn/auth:/vpn-credentials
      - /root/silverbox/containers/vpn-proxy/host-key:/ssh-host-key
----
<1> Replace `{SB_VPN_SUBNET}` with the subnet for the Docker VPN network.
<2> Replace `{SB_ALPINE_VERSION}` with the actual latest `alpine` image version (can be checked at the Docker Hub).
Don't use `latest` here as it makes setup non-deterministic and makes it harder to maintain and upgrade.
<3> Replace `{SB_IP}` and `{SB_VPN_PROXY_PORT}` with the actual values.
<4> Replace `{SB_VPN_PROXY_ADDR}` with desired VPN proxy container address.

Next, create a file named `Dockerfile` with the following content:

./root/silverbox/containers/vpn-proxy/Dockerfile
[source,dockerfile,subs="attributes+"]
----
ARG version=latest

FROM alpine:$version

RUN apk --no-cache --no-progress upgrade && \
    apk --no-cache --no-progress add bash iptables tini shadow openvpn openssh && \
    addgroup -S vpn && \
    adduser proxytunnel -D --shell /sbin/nologin && \
    usermod -p '*' proxytunnel && \
    rm -rf /tmp/*

COPY docker-entrypoint.sh /usr/local/bin/
COPY sshd_config /etc/ssh/
COPY proxy_tunnel.pub /home/proxytunnel

RUN chown proxytunnel /home/proxytunnel/proxy_tunnel.pub

HEALTHCHECK --interval=120s --timeout=20s --start-period=120s CMD ping 1.1.1.1 -c 1 # <1>

VOLUME ["/vpn-profiles", "/vpn-credentials"]

EXPOSE {SB_VPN_PROXY_PORT}/tcp # <2>

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/docker-entrypoint.sh"]
----
<1> Feel free to customize health check command.
<2> Replace `{SB_VPN_PROXY_PORT}` with some port number of your choice (e.g. 12345).

Next, create a `sshd_config` file with the following content:

./root/silverbox/containers/vpn-proxy/sshd_config
[subs="attributes+"]
----
Protocol 2

HostKey /etc/ssh/ssh_host_ed25519_key

KexAlgorithms curve25519-sha256@libssh.org
Ciphers aes128-gcm@openssh.com # <1>
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

AddressFamily inet
ListenAddress {SB_VPN_PROXY_ADDR}:{SB_VPN_PROXY_PORT} # <2>

LogLevel ERROR
LoginGraceTime 1m
PermitRootLogin no
MaxAuthTries 4
MaxSessions 5
AuthenticationMethods publickey
PubkeyAuthentication yes
HostbasedAuthentication no
IgnoreRhosts yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
X11Forwarding no
Banner none
AllowAgentForwarding no
AllowTcpForwarding yes
PermitTTY no

AllowUsers proxytunnel
AuthorizedKeysFile /home/proxytunnel/proxy_tunnel.pub
----
<1> This cipher was chosen after testing performance of different ciphers on the given hardware.
It offers reasonable performance while maintaining decent security.
Feel free to change the cipher if you need to.
<2> Replace `{SB_VPN_PROXY_ADDR}:{SB_VPN_PROXY_PORT}` with some IP address from the `{SB_VPN_SUBNET}`
and the `{SB_VPN_PROXY_PORT}` port number.

Next, create a `docker-entrypoint.sh` file with the following content:

./root/silverbox/containers/vpn-proxy/docker-entrypoint.sh
[source,bash,subs="attributes+"]
----
#!/usr/bin/env bash

function configure_iptables()
{
    set -e

    local config_file="$1"
    local host=$(awk '/^remote / {print $2}' "$config_file")
    local port=$(awk '/^remote / && NF ~ /^[0-9]*$/ {print $NF}' "$config_file")

    if [ -z "$port" ]; then
        echo "-- No port number specified in the VPN profile file"
        exit 1
    else
        echo "-- Setting up firewall rules for VPN server $host on port $port"
    fi

    iptables --flush
    iptables --delete-chain

    iptables --policy INPUT DROP
    iptables --policy OUTPUT DROP
    iptables --policy FORWARD DROP

    iptables -A INPUT -i lo -j ACCEPT
    iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
# <1>
    iptables -A INPUT -p tcp --dport {SB_VPN_PROXY_PORT} -m conntrack --ctstate NEW -m recent --set --name SSH --mask 255.255.255.255 --rsource
    iptables -A INPUT -p tcp --dport {SB_VPN_PROXY_PORT} -m conntrack --ctstate NEW -m recent --update --seconds 30 --hitcount 6 --name SSH --mask 255.255.255.255 --rsource -j DROP
    iptables -A INPUT -p tcp --dport {SB_VPN_PROXY_PORT} -m conntrack --ctstate NEW -j ACCEPT

    iptables -A OUTPUT -o lo -j ACCEPT
    iptables -A OUTPUT -o tun0 -j ACCEPT
    iptables -A OUTPUT -o eth0 -d {SB_SUBNET} -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT # <2>
    iptables -A OUTPUT -o eth0 -p tcp -d $host --dport $port -m owner --gid-owner vpn -j ACCEPT

    set +e
}

function run_sshd()
{
    set -e

    if [ ! -f "/etc/ssh/ssh_host_ed25519_key" ]; then
        if [ ! -f "/ssh-host-key/ssh_host_ed25519_key" ]; then
          echo "-- Generating host key"
          ssh-keygen -f /etc/ssh/ssh_host_ed25519_key -N '' -t ed25519
          cp /etc/ssh/ssh_host_ed25519_key /ssh-host-key/ssh_host_ed25519_key
        else
          cp /ssh-host-key/ssh_host_ed25519_key /etc/ssh/ssh_host_ed25519_key
        fi
    fi

    echo "-- Adding oute back to LAN"
    ip route add {SB_SUBNET} via \{DOCKER_VPN_NETWORK_GW} # <3>

    echo "-- Starting SSH server"
    /usr/sbin/sshd

    set +e
}

if [[ $# -ge 1 ]]; then
    exec "$@"
else
    if [ -f /vpn-profiles/profile ]; then
        echo "-- Profile file found: only it will be used"
        PROFILE_FILE="/vpn-profiles/profile"
    else
        echo "-- Profile file not found: random profile file will be picked"
        PROFILE_FILE="$(ls -1 /vpn-profiles/*.ovpn | shuf -n 1)"
        echo "-- Selected profile file: $PROFILE_FILE"
    fi

    configure_iptables "$PROFILE_FILE"
    run_sshd

    exec sg vpn -c "openvpn --config $PROFILE_FILE --verb 1 --auth-user-pass /vpn-credentials/credentials --auth-nocache"
fi
----
<1> This block establishes rate limiting for incoming SSH connections.
Replace `{SB_VPN_PROXY_PORT}` with the actual port number in it.
<2> Replace `{SB_SUBNET}` with your LAN subnet.
<3> Replace `{SB_SUBNET}` with your LAN subnet.
Also, replace `\{DOCKER_VPN_NETWORK_GW}` with the default gateway for your `{SB_VPN_SUBNET}`
(ends with 1, i.e. for network 172.18.0.0/12 it will be 172.18.0.1).

Mark `docker-entrypoint.sh` as executable:

----
sudo chmod a+x docker-entrypoint.sh
----

==== Generating Client SSH Key
This section describes how to generate client SSH key that will be used to authenticate to the
SSH server that is running inside the container.

On the client PC (from which you will connect to the proxy) generate a new SSH key with the following command
(don't use any passphrase, as the tunnel will be established automatically):

----
ssh-keygen -t ed25519 -f ~/.ssh/silverbox-proxy-tunnel -C "Silverbox proxy tunnel key"
----

Copy public key to the server:

[subs="attributes+"]
----
scp ~/.ssh/silverbox-proxy-tunnel $USER@{SB_IP}:proxy_tunnel.pub
----

Move this file under the `/root/silverbox/containers/vpn-proxy` directory and make it only readable by the root:

----
sudo chown root:root proxy_tunnel.pub
sudo chmod 400 proxy_tunnel.pub
----

