[[server_overview_goals]]
=== Goals
Main goals that greatly affected overall design decisions for the server are:

Simplicity::
Where possible, this document prefers more simple solutions, i.e. solutions that involve less configuration,
fewer components and minimum bloat.
Stability::
The server design is heavily focused on stability of configuration and setup.
While there are many fancy new tools and programs that could be used, vast majority of them have very short life span,
minimal to no backward/forward compatibility, support, documentation, security updates etc.
Instead, the choices were made in favor of mature, stable, proven software, that doesn't break compatibility every
minor release.
Security::
Major considerations were given to security when designing the server setup.
While I think the solution in general is secure enough for home use, I still would not recommend to keep any
sensitive information on the server.
Minimal maintenance::
Another major focus was keeping the server maintenance as small as possible.
This goes hand in hand with stability, and also relies on tools and automation to keep server maintenance as minimal
as possible.

It is important to mention that this server is *not* a:

NAS::
It is not intended to be used for safe storage of massive amounts of data (at least no in the described configuration).
Media Server::
It is not running anything related to the media server, no Cody, not even X server.
Proprietary Server::
It is not running any proprietary, closed-source solutions, even if they are free (so no Plex).

