=== Installation
This section describes how to install and run Nextcloud.

==== Preparing Directory Structure
The very first step is to create directories that will be mapped inside Nextcloud Docker containers:

[subs="attributes+"]
----
sudo mkdir -p /srv/nextcloud/db
sudo mkdir /srv/nextcloud/html
sudo mkdir /srv/nextcloud/data
sudo chown {SB_WWW_DATA_UID} /srv/nextcloud/data # <1>
sudo chmod 750 -R /srv/nextcloud
----
<1> `{SB_WWW_DATA_UID}` is the UID of the `www-data` user (inside Apache httpd and Nextcloud FPM containers).

All the Nextcloud data (including database, static files and user data)
will be stored under the `/srv/nextcloud` directory in the following way:

db::
The `db` subdirectory will store PostgreSQL database files.
html::
The `html` subdirectory will store static HTML/PHP files.
data::
The `data` subdirectory will store user's data.

NOTE: It is important to keep these directories owned by the root and have restrictive permissions
since content inside them will be owned by the `www-data` (UID `{SB_WWW_DATA_UID}`) user from the Docker containers.

==== Preparing Images
Create a directory for Nextcloud containers files:

----
sudo mkdir /root/silverbox/containers/nextcloud
sudo chmod 700 /root/silverbox/containers/nextcloud
----

Inside it, create the `docker-compose.yml` file with the following content:

./root/silverbox/containers/nextcloud/docker-compose.yml
[source,yaml,subs="attributes+"]
----
version: '3.8'

networks:
  default:
    name: nextcloud
    driver: bridge
    ipam:
      config:
        - subnet: {SB_NEXTCLOUD_SUBNET} # <1>

services:
  nextcloud-db:
    container_name: nextcloud-db
    image: postgres:{SB_POSTGRES_VERSION} # <2>
    restart: on-failure:5
    shm_size: 256mb
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '3'
    volumes:
      - /srv/nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=\{POSTGRES_PASSWORD} # <3>
      - POSTGRES_DB=nextcloud
      - POSTGRES_INITDB_ARGS="--data-checksums"

  nextcloud-fpm:
    container_name: nextcloud-fpm
    build:
      context: ./nextcloud-fpm
      args:
        version: '{SB_NEXTCLOUD_FPM_VERSION}' # <4>
    restart: on-failure:5
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '3'
    depends_on:
      - nextcloud-db
    volumes:
      - /srv/nextcloud/html:/var/www/html
      - /srv/nextcloud/data:/data
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=\{POSTGRES_PASSWORD} # <5>
      - NEXTCLOUD_DATA_DIR=/data
      - NEXTCLOUD_UPDATE=1
      - NEXTCLOUD_TRUSTED_DOMAINS='{SB_NEXTCLOUD_DOMAIN}:{SB_NEXTCLOUD_PORT}' # <6>

  nextcloud-web:
    container_name: nextcloud-web
    build:
      context: ./httpd
      args:
        version: '{SB_HTTPD_VERSION}' # <7>
    restart: on-failure:5
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '3'
    depends_on:
      - nextcloud-fpm
    volumes:
      - /srv/nextcloud/html:/usr/local/apache2/htdocs
      - /etc/letsencrypt/live/{SB_NEXTCLOUD_DOMAIN}:/certs/live/{SB_NEXTCLOUD_DOMAIN} # <8>
      - /etc/letsencrypt/archive/{SB_NEXTCLOUD_DOMAIN}:/certs/archive/{SB_NEXTCLOUD_DOMAIN} # <9>
    ports:
      - "{SB_IP}:{SB_NEXTCLOUD_PORT}:443" # <10>
----
<1> Replace `{SB_NEXTCLOUD_SUBNET}` with the actual subnet you want to use for the Nextcloud.
<2> Replace `{SB_POSTGRES_VERSION}` with the actual latest `postgres` (Debian based) image version (can be checked at the Docker Hub).
You can double check if this version is supported by the Nextcloud in the Nextcloud documentation.
<3> Replace `\{POSTGRES_PASSWORD}` with some random password.
<4> Replace `{SB_NEXTCLOUD_FPM_VERSION}` with the actual latest `nextcloud-fpm` (Debian based) image version (can be checked at the Docker Hub).
<5> Replace `\{POSTGRES_PASSWORD}` with the same password as above.
<6> Replace `{SB_NEXTCLOUD_DOMAIN}` with your Nextcloud domain name and
`{SB_NEXTCLOUD_PORT}` with the port number you chose to use for the Nextcloud
(the Nextcloud web server will listen on this port).
<7> Replace `{SB_HTTPD_VERSION}` with the actual latest `httpd` (Debian based) image version (can be checked at the Docker Hub).
<8> Replace `{SB_NEXTCLOUD_DOMAIN}` with the actual domain name for the Nextcloud.
<9> Same as above.
<10> Replace `{SB_IP}` and `{SB_NEXTCLOUD_PORT}` with the actual values.

[[nextcloud_httpd_config]]
===== HTTPD
Create a directory for the customized Apache HTTPD image:

----
sudo mkdir /root/silverbox/containers/nextcloud/httpd
sudo chmod 700 /root/silverbox/containers/nextcloud/httpd
----

Inside it, create the `Dockerfile` file with the following content:

./root/silverbox/containers/nextcloud/httpd/Dockerfile
[source,dockerfile,subs="attributes+"]
----
ARG version=latest

FROM httpd:$version

ARG WWW_DATA_UID={SB_WWW_DATA_UID} # <1>
ARG WWW_DATA_GID={SB_WWW_DATA_GID}

RUN [ "$(id -u www-data)" -eq "$WWW_DATA_UID" ] && [ "$(id -g www-data)" -eq "$WWW_DATA_GID" ] || exit 1 # <2>

COPY httpd.conf /usr/local/apache2/conf/httpd.conf
----
<1> These UID and GID are currently standard Debian based HTTPD image.
<2> Extra precaution to ensure that `www-data` UID/GID are what we expect (in case they change in newer images).

Next, create the `httpd.conf` file with the following content:

./root/silverbox/containers/nextcloud/httpd/httpd.conf
[source,apache,subs="attributes+"]
----
ServerName {SB_NEXTCLOUD_DOMAIN}:{SB_NEXTCLOUD_PORT} # <1>
ServerRoot "/usr/local/apache2"

Listen 443

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule env_module modules/mod_env.so
LoadModule headers_module modules/mod_headers.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule dir_module modules/mod_dir.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule ssl_module modules/mod_ssl.so
LoadModule status_module modules/mod_status.so
LoadModule http2_module modules/mod_http2.so

User www-data
Group www-data

Protocols h2 http/1.1

SSLEngine On
SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
SSLHonorCipherOrder On
SSLProtocol -all +TLSv1.3 +TLSv1.2
SSLUseStapling on
SSLStaplingCache "shmcb:/usr/local/apache2/logs/ssl_stapling(128000)"
SSLSessionTickets Off
SSLSessionCache "shmcb:/usr/local/apache2/logs/ssl_scache(512000)"
SSLSessionCacheTimeout 300
SSLCertificateFile /certs/live/{SB_NEXTCLOUD_DOMAIN}/fullchain.pem # <2>
SSLCertificateKeyFile /certs/live/{SB_NEXTCLOUD_DOMAIN}/privkey.pem # <3>

<Directory />
    AllowOverride none
    Require all denied
</Directory>

DocumentRoot "/usr/local/apache2/htdocs"
DirectoryIndex index.html

<Directory "/usr/local/apache2/htdocs">
    Options FollowSymLinks
    AllowOverride All
    Require all granted

    <FilesMatch \.php$>
        ProxyFCGISetEnvIf "true" SCRIPT_FILENAME "/var/www/html%{reqenv:SCRIPT_NAME}"
        SetHandler proxy:fcgi://nextcloud-fpm:9000
    </FilesMatch>

    Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains; preload"
</Directory>

<Location "/apache-server-status.html">
    SetHandler server-status
    Require ip {SB_IP} # <4>
</Location>

<Files ".ht*">
    Require all denied
</Files>

ProxyTimeout 3600

<Proxy "fcgi://nextcloud-fpm/">
</Proxy>

RewriteEngine on
RewriteCond %\{QUERY_STRING} ^monit$ # <5>
RewriteCond %\{REQUEST_METHOD} HEAD
RewriteCond %\{REQUEST_URI} ^/$
RewriteRule .* - [env=dont_log]

SetEnvIf Request_URI "^/apache-server-status.html$" dont_log # <6>

ErrorLog /proc/self/fd/2
LogLevel warn
LogFormat "%h %l %u %t \"%r\" %>s %b \"%\{Referer}i\" \"%\{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog /proc/self/fd/1 common env=!dont_log

TypesConfig conf/mime.types
AddType application/x-compress .Z
AddType application/x-gzip .gz .tgz

Include conf/extra/httpd-mpm.conf

RewriteEngine On
RewriteCond %\{REQUEST_METHOD} ^TRACK
RewriteRule .* - [F]

RequestHeader unset Proxy early

ServerTokens Prod
TraceEnable off
----
<1> Replace `{SB_NEXTCLOUD_DOMAIN}` and `{SB_NEXTCLOUD_PORT}` with the actual values.
<2> Replace `{SB_NEXTCLOUD_DOMAIN}` with the actual value.
<3> Same as above.
<4> Replace `{SB_IP}` with the actual value.
<5> This rewrite block matches HEAD requests to root with query string equal to "monit" and sets environment variable
`dont_log` that is later used to filter such requests from the web server logs.
This is useful to filter out requests done by Monit from log, as they will flood logs otherwise.
For security reasons, you can replace "monit" string in the first `RewriteCond` with a random alphanumeric string,
that you will also put in the Monit configuration for Nextcloud monitoring.
<6> This rule is used to filter out requests to Apache server status page from logs, as it only used by Monit.

NOTE: If you decide to customize this config file and add some extra modules, make sure you are not using
modules that don't work well with Nextcloud.
More info here: https://docs.nextcloud.com/server/stable/admin_manual/issues/general_troubleshooting.html#web-server-and-php-modules.

===== Nextcloud PHP FPM
Create a directory for the customized Nextcloud PHP FPM image:

----
sudo mkdir /root/silverbox/containers/nextcloud/nextcloud-fpm
sudo chmod 700 /root/silverbox/containers/nextcloud/nextcloud-fpm
----

Inside it, create the `Dockerfile` file with the following content:

./root/silverbox/containers/nextcloud/nextcloud-fpm/Dockerfile
[source,dockerfile,subs="attributes+"]
----
ARG version=fpm

FROM nextcloud:$version

ARG NFSSHARE_GID=\{GID} # <1>

ARG WWW_DATA_UID={SB_WWW_DATA_UID} # <2>
ARG WWW_DATA_GID={SB_WWW_DATA_GID}

ARG PHP_FPM_CONF=/usr/local/etc/php-fpm.d/www.conf

RUN [ "$(id -u www-data)" -eq "$WWW_DATA_UID" ] && [ "$(id -g www-data)" -eq "$WWW_DATA_GID" ] || exit 1 # <3>

RUN apt-get update && \
    apt-get install -y --no-install-recommends supervisor libmagickcore-6.q16-6-extra && \
    mkdir /var/log/supervisord /var/run/supervisord && \
    sed -i 's/-l\s\+[0-9]\+/-l 5/' /cron.sh && \ # <4>
    sed -i 's/^\(pm.max_children\s*=\)\s*[0-9]\+/\1 20/' $\{PHP_FPM_CONF} && \ # <5>
    sed -i 's/^\(pm.start_servers\s*=\)\s*[0-9]\+/\1 5/' $\{PHP_FPM_CONF} && \
    sed -i 's/^\(pm.min_spare_servers\s*=\)\s*[0-9]\+/\1 4/' $\{PHP_FPM_CONF} && \
    sed -i 's/^\(pm.max_spare_servers\s*=\)\s*[0-9]\+/\1 10/' $\{PHP_FPM_CONF} && \
    addgroup --gid $\{NFSSHARE_GID} nfsshare && \
    usermod www-data -aG nfsshare

COPY supervisord.conf /etc/supervisor/supervisord.conf

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
----
<1> Replace the `\{GID}` with the GID of your `{SB_NFS_GROUP}` group.
This is so that Nextcloud can access files in the NFS directory owned by the `{SB_NFS_GROUP}`.
<2> These UID and GID are currently standard Debian based image.
<3> Extra precaution to ensure that `www-data` UID/GID are what we expect (in case they change in newer images).
<4> This is to reduce verbosity of the Cron logs to 5. Adjust if necessary.
<5> Update PHP FPM configuration, feel free to adjust these values according to your needs.
More information at Nextcloud [server tuning](https://docs.nextcloud.com/server/stable/admin_manual/installation/server_tuning.html#tune-php-fpm) documentation.

Create the `supervisord.conf` file with the following content:

./root/silverbox/containers/nextcloud/nextcloud-fpm/supervisord.conf
[source,ini]
----
[supervisord]
nodaemon=true
logfile=/var/log/supervisord/supervisord.log
pidfile=/var/run/supervisord/supervisord.pid
childlogdir=/var/log/supervisord/
logfile_maxbytes=10MB
logfile_backups=0
loglevel=info
user=root

[program:php-fpm]
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
command=php-fpm

[program:cron]
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
command=/cron.sh
----

==== Adding Firewall Rule
To add Firewall rule to allow accessing the Nextcloud do:

[subs="attributes+"]
----
sudo ufw allow proto tcp to any port {SB_NEXTCLOUD_PORT} comment "Nextcloud"
----

==== Adding Port Forwarding Rule
To access Nextcloud from the outside, add the port forwarding rule on your router,
to forward port `{SB_NEXTCLOUD_PORT}` to `{SB_IP}:{SB_NEXTCLOUD_PORT}`.

==== Running Nextcloud
To pull/build all necessary images and run the containers do:

----
sudo docker compose -f /root/silverbox/containers/nextcloud/docker-compose.yml up -d
----

Verify that all containers have started successfully and check logs for errors:

----
sudo docker ps
sudo docker logs nextcloud-db
sudo docker logs nextcloud-web
sudo docker logs nextcloud-fpm
----

NOTE: There might be some errors in the PostgreSQL container logs, related to the unique constrain violation
on the `lock_key_index`.
This is due to the following bug in the Nextcloud: https://github.com/nextcloud/server/issues/6343.
Hopefully, this bug will eventually be fixed.

Open Nextcloud web interface `https://{SB_NEXTCLOUD_DOMAIN}:{SB_NEXTCLOUD_PORT}` and create admin account.

==== Automatic Containers Startup
To start containers automatically (in the correct order)
on boot create the `/etc/systemd/system/nextcloud-start.service` file with the following content:

./etc/systemd/system/nextcloud-start.service
----
[Unit]
Description=Start Nextcloud
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
ExecStart=/usr/bin/docker compose -f /root/silverbox/containers/nextcloud/docker-compose.yml up -d

[Install]
WantedBy=multi-user.target
----

Enable the service, so that it will be started on system boot:

----
sudo systemctl daemon-reload
sudo systemctl enable nextcloud-start.service
----

