[[generating_custom_document]]
=== Generating Custom Document
This document contains a lot of placeholder values that will have to be replaced with the actual values,
specific to your setup. Some examples of such values are host names, IP addresses, subnets, usernames etc.
It may be cumbersome to manually keep track of what needs to be replaced with what,
especially when copying scripts or configuration files.

Fortunately, you can generate your own version of this document
where all placeholders will be automatically replaced with the actual values that you want.

This can easily be done in three steps using Docker:

. Get the source code of this document from Git:
+
----
git clone https://gitlab.com/kosheo/silverbox-server.git
----

. Edit `silverbox-server/parameters.adoc` file and replace placeholder values with the values you want.
. Run disposable Docker container with Asciidoctor to compile the document to desired output:
.. For HTML output:
+
----
docker run -it --rm -v $(pwd)/silverbox-server:/documents asciidoctor/docker-asciidoctor asciidoctor silverbox-server.adoc
----

.. For PDF output:
+
----
docker run -it --rm -v $(pwd)/silverbox-server:/documents asciidoctor/docker-asciidoctor asciidoctor-pdf silverbox-server.adoc
----

This should produce output file (`silverbox-server.html` or `silverbox-server.pdf`) in the `silverbox-server`
directory, where all the placeholders replaced with your values.

Now you can mostly just copy-paste code snippets without having to manually edit them first.

